### ISSUE TITLE
Force control on uneven surface with Franka Emika

### ISSUE THREAD

**Issue by albic98** [fzi-forschungszentrum-informatik/cartesian_controllers#169]
Hello, I integrated this controllers on Franka Emika Panda and would like to use it while moving on some 3D uneven surface. I want to track the shape of the surface while having constant contact. Is this possible with the compliance controller which is here? And how would you suggest to do it?

**Comment by matthias-mayr** [comment]
We have an example for an even surface and a UR5 with this controller package [in this paper](https://ieeexplore.ieee.org/document/10260413) [(arXiv)](https://arxiv.org/abs/2308.14206). A video of it is also quickly shown in the ROSCon talk [here](https://vimeo.com/879001825/2a0e9d5412#t=867). A few seconds later you also see one of our KUKA iiwas doing a similar wiping task.  
Since the iiwa - like the Panda - allows us to use torque control, we used our [Cartesian impedance controller](https://github.com/matthias-mayr/Cartesian-Impedance-Controller), which give us very stable behavior w.r.t oscillations.  A short paper about this controller just got [published yesterday with JOSS](https://joss.theoj.org/papers/10.21105/joss.05194). Unfortunately it's not ported to ROS 2 yet.

I've always been interested in uneven surfaces, but haven't tried it yet myself. What we did for both demos with the even surface is to disable stiffness in the direction to the surface and apply a force. Then we execute our trajectory and with the stiffness in both horizontal direction, the end effector follows the reference trajectory. More is in the paper.
