### ISSUE TITLE
Tool0 and tool0_controller are not aligned using custom TCP

### ISSUE THREAD

**Issue by LordAcrobaticTurtle** [fzi-forschungszentrum-informatik/cartesian_controllers#98]
**Problem description**
Hi @stefanscherzinger 

As you suggested opening a new issue. Copy pasting the previous description used previously from  #73 

I've been using cartesian-controllers for my undergrad thesis it is wonderful thank you.

I am wondering how you modified the kinematic tree for your UR robot? I haven't been able to work it out nor find any resources to help.
Hopefully I attached this image correctly, but this shows the current Tf tree. My TCP position is linked to "tool0_controller", so I assume I need to move it to the end of the other branch, but I am unsure how.
I'd greatly appreciate any advice.

[frames (1).pdf](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/files/9815902/frames.1.pdf)

I'm using the compliance controller but I believe the controller yaml is correct and I have attached it for reference. 
I have run ur_calibration and I pass the generated yaml file to the ur_robot_driver when I launch the launch it using this command
roslaunch ur_robot_driver ur5e_bringup.launch robot_ip:=192.168.0.100 kinematics_config:="/home/mtrn4230/repos/Thesis_robotic_drilling/calibration.yaml"

However when I inspect the frames using rosrun tf2_tools echo.py, tool0 to tool0_controller does not give an identity transform.

Just for context, I'm using a UR5e arm, I "taught" the robot a new TCP position on the pendant and I set that to be active when I am using the robot. When it is set to the default TCP the arm behaves as expected, and tool0 + tool0_controller are aligned. This is only a problem after I activate my custom TCP.

**Software versions**
 -  **Commit**: 14249f58ae2b3b8bddb6afdd4df9cae4149ead13
 - **OS**: Ubuntu 18.04
 - **version**: ROS1 Melodic. 

@stefanscherzinger  Please forgive my naivety, but is there are guide for updating the URDF links as you suggested in #73 ??

**Comment by stefanscherzinger** [comment]
> is there are guide for updating the URDF links as you suggested in https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/issues/73 ??

That's in fact a very basic thing. Here's the workflow (logic) on a higher level:
1) Many applications require some form of `robot_description`. Users specify all sorts of custom elements in it, e.g. static objects, robots and tools for their robots.
2) When working with the Universal Robots, there's a very basic *default*  `robot_description` that gets used implicitly when you start the driver. Normally, when setting-up a custom application, you would embed this description in your own (more advanced) one.
3) This robot description is parsed by the `robot_state_publisher`, which completes the TF tree with the information it gets from the `joint_states` topic. The result is the TF tree that you reference in your *frames (1).pdf*.
4) The `cartesian_controllers` will also parse this `robot_description`. Depending on the type of controller, different URDF links need to be specified in that description. [Here](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/ros2/cartesian_controller_simulation/config/controller_manager.yaml#L29)'s more documentation on the individual links that the controllers use. Of course, you can only specify links that *exist* in the `robot_description`.
5) Depending on your use case, you just add URDF links that you wish to be present to the `robot_description`. You could either edit them directly in the driver's `robot_description` (not recommended, because you cannot commit them there. I'm not sure at the moment where that lies anyway. You would have to find the respective file in your ROS workspace) or in your own package, in which you customize the default `robot_description`. See link below for an example.
6) When your refined `robot_description` is loaded and processed by all elements that require it, you'll see the new links in your TF graph.

---

I started an example repository [here](https://github.com/stefanscherzinger/cartesian_controllers_ur_robots). Have a look at my custom [urdf](https://github.com/stefanscherzinger/cartesian_controllers_ur_robots/blob/main/urdf/test_setup.urdf.xacro) configuration for the `robot_description`. I use `grasping_center` that I defined myself. This is eventually passed as `robot_description_file` to the driver. Try to trace this in the configuration files.

**Comment by LordAcrobaticTurtle** [comment]
@stefanscherzinger  You're an absolute champion cheers mate. 

For anyone else with a similar issue,
After grabbing the repository above and making it work for my file locations + names etc, the last thing I needed to do to make it compliant around the custom TCP was to change the ft_sensor_ref_link and the compliance_ref_link in the compliance controller yaml file to the newly defined "grasping center" link that is in the .urdf.xacro file. 

I grabbed the correct xyz and rpy transform for the frame by inspecting the TF tree and finding the transform between the tool0 and tool0_controller frames as explained at the bottom of the comments in #73
